# Generated by Django 4.2.3 on 2023-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('sub_typ', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('reward', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
