# Generated by Django 4.2.3 on 2023-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_hackathon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
